version: '3.8'
services:

  fastapi:
    build:
      context: ../backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
 
  nginx:
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
